services:
  api:
    build: ./api
    container_name: api
    restart: always
    environment:
      - APP_NAME=CoinPurse2
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - 80:8080
    depends_on:
      - api
